// build.mjs — generates js/config.js from the API_BASE_URL environment variable.
// Runs on Vercel via the buildCommand in vercel.json.
// Local: reads .env first (process.env / Vercel env vars always win over .env).
import { writeFileSync, readFileSync, existsSync } from "node:fs";

function loadEnv() {
  const envPath = new URL("./.env", import.meta.url);
  if (!existsSync(envPath)) return false;
  for (const line of readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([\w.-]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    const val = m[2].trim().replace(/^['"]|['"]$/g, "");
    // process.env (Vercel / system) wins; .env is only a local fallback
    if (process.env[m[1]] === undefined) process.env[m[1]] = val;
  }
  return true;
}

const foundEnv = loadEnv();
// Fallback to the deployed Render backend so production builds work even if the
// Vercel "API_BASE_URL" env var is missing. An explicit env var still wins.
const DEFAULT_API_BASE = "https://ai-doctor-virtual-medical-assistant.onrender.com";
const apiBase  = (process.env.API_BASE_URL || DEFAULT_API_BASE).replace(/\/+$/, "");

console.log(`[build] API_BASE_URL="${apiBase}" (source: ${process.env.API_BASE_URL ? (foundEnv ? ".env / environment variable" : "environment variable") : "built-in default"})`);

const contents = `// AUTO-GENERATED by build.mjs — do not edit by hand. Run: npm run build
window.APP_CONFIG = {
  API_BASE_URL: ${JSON.stringify(apiBase)},
};
`;

writeFileSync(new URL("./js/config.js", import.meta.url), contents);
console.log(`[build] js/config.js written.`);
