#!/usr/bin/env python3
"""AI Doctor - local application runner.

Starts the *complete* local stack with a single command:

    python app.py

  * Backend  - FastAPI (Backend/app) on http://127.0.0.1:8000
  * Frontend - static site (Frontend/) on http://127.0.0.1:3000

Local mode deliberately differs from the Render deployment: every heavy local
model (TensorFlow fracture detection, PaddleOCR lab-report reading, Whisper
speech-to-text) is auto-enabled when its dependency is importable, so running
locally gives you the full feature set. Nothing here talks to the deployed
backend - the frontend is pointed at the local API.

Flags:
    --backend-port N   backend port (default 8000, or $PORT)
    --frontend-port N  frontend port (default 3000)
    --no-browser       do not open a browser window
    --api-only         run the backend only
    --reload           auto-reload the backend on code changes
"""

from __future__ import annotations

import argparse
import functools
import http.server
import importlib.util
import json
import os
import socket
import socketserver
import sys
import threading
import webbrowser
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BACKEND_DIR = ROOT / "Backend"
FRONTEND_DIR = ROOT / "Frontend"


# -- Environment ----------------------------------------------------------
def load_dotenv_files() -> None:
    """Load Backend/.env. Real environment variables always win over the file."""
    for env_path in (BACKEND_DIR / ".env",):
        if not env_path.exists():
            continue
        for raw in env_path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            if not key.replace("_", "").isalnum():
                continue
            value = value.split(" #")[0].strip().strip("'\"")
            os.environ.setdefault(key, value)


def detect_local_models() -> dict[str, bool]:
    """Enable each local-model feature when its dependency is importable."""
    def have(mod: str) -> bool:
        try:
            return importlib.util.find_spec(mod) is not None
        except (ImportError, ValueError):
            return False

    return {
        "ENABLE_FRACTURE": have("tensorflow"),
        "ENABLE_OCR": have("paddleocr"),
        "ENABLE_VOICE": have("whisper"),
    }


def configure_local_environment(backend_port: int, frontend_port: int) -> dict[str, bool]:
    """Apply local-development defaults. Explicit env vars are never overridden."""
    os.environ.setdefault("ENVIRONMENT", "development")
    os.environ["PORT"] = str(backend_port)

    detected = detect_local_models()
    for key, available in detected.items():
        # An explicit ENABLE_* in the environment/.env wins over auto-detection.
        if os.environ.get(key, "").strip():
            detected[key] = os.environ[key].strip().lower() in ("1", "true", "yes", "on")
        else:
            os.environ[key] = "true" if available else "false"

    origins = {
        "http://localhost:%d" % frontend_port, "http://127.0.0.1:%d" % frontend_port,
        "http://localhost:%d" % backend_port, "http://127.0.0.1:%d" % backend_port,
        "http://localhost:5500", "http://127.0.0.1:5500",
    }
    existing = os.environ.get("ALLOWED_ORIGINS", "").strip()
    if existing and existing != "*":
        origins.update(o.strip() for o in existing.split(",") if o.strip())
    os.environ["ALLOWED_ORIGINS"] = ",".join(sorted(origins))
    return detected


def write_frontend_config(backend_port: int) -> None:
    """Point the static frontend at the *local* backend (no Node required)."""
    api_base = "http://127.0.0.1:%d" % backend_port
    config = (
        "// AUTO-GENERATED by app.py (local run) - do not edit by hand.\n"
        "window.APP_CONFIG = {\n"
        "  API_BASE_URL: %s,\n"
        "};\n" % json.dumps(api_base)
    )
    target = FRONTEND_DIR / "js" / "config.js"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(config, encoding="utf-8")


# -- Checks ---------------------------------------------------------------
def port_is_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind(("127.0.0.1", port))
            return True
        except OSError:
            return False


def preflight() -> None:
    missing = [m for m in ("fastapi", "uvicorn", "openai", "reportlab", "gtts")
               if importlib.util.find_spec(m) is None]
    if missing:
        sys.exit(
            "Missing required packages: " + ", ".join(missing)
            + "\nInstall them with:  pip install -r Backend/requirements-local.txt"
        )
    if not (BACKEND_DIR / "app" / "main.py").exists():
        sys.exit("Backend application not found at %s" % (BACKEND_DIR / "app" / "main.py"))


# -- Frontend static server -----------------------------------------------
class _QuietHandler(http.server.SimpleHTTPRequestHandler):
    """Static handler with clean-URL support and no-cache headers for dev."""

    def log_message(self, fmt, *args):
        pass

    def end_headers(self):
        self.send_header("Cache-Control", "no-store, max-age=0")
        super().end_headers()

    def translate_path(self, path: str) -> str:
        local = super().translate_path(path)
        # "/chatbot" -> "/chatbot.html" (matches Vercel's cleanUrls: true)
        if not os.path.exists(local) and not path.endswith("/"):
            candidate = local + ".html"
            if os.path.exists(candidate):
                return candidate
        return local


class _ReusableServer(socketserver.ThreadingTCPServer):
    daemon_threads = True
    allow_reuse_address = True


def start_frontend(port: int) -> _ReusableServer:
    handler = functools.partial(_QuietHandler, directory=str(FRONTEND_DIR))
    server = _ReusableServer(("127.0.0.1", port), handler)
    threading.Thread(target=server.serve_forever, daemon=True, name="frontend").start()
    return server


# -- Entry point ----------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(description="Run the complete AI Doctor app locally.")
    parser.add_argument("--backend-port", type=int, default=int(os.environ.get("PORT") or 8000))
    parser.add_argument("--frontend-port", type=int, default=3000)
    parser.add_argument("--no-browser", action="store_true")
    parser.add_argument("--api-only", action="store_true")
    parser.add_argument("--reload", action="store_true")
    args = parser.parse_args()

    load_dotenv_files()
    preflight()

    # Import the backend package from Backend/ without installing it.
    # The repo root must NOT stay ahead of it on sys.path: this file is named
    # app.py and would otherwise shadow the Backend/app package.
    sys.path[:] = [p for p in sys.path if Path(p or ".").resolve() != ROOT]
    sys.path.insert(0, str(BACKEND_DIR))
    # Propagate to uvicorn's --reload subprocess, which re-executes Python.
    existing_pythonpath = os.environ.get("PYTHONPATH", "")
    os.environ["PYTHONPATH"] = (
        str(BACKEND_DIR) + (os.pathsep + existing_pythonpath if existing_pythonpath else "")
    )
    os.chdir(BACKEND_DIR)

    features = configure_local_environment(args.backend_port, args.frontend_port)

    if not port_is_free(args.backend_port):
        sys.exit("Port %d is already in use. Try: python app.py --backend-port 8001" % args.backend_port)

    frontend_url = None
    if not args.api_only:
        if not FRONTEND_DIR.is_dir():
            sys.exit("Frontend directory not found at %s" % FRONTEND_DIR)
        if not port_is_free(args.frontend_port):
            sys.exit("Port %d is already in use. Try: python app.py --frontend-port 3001" % args.frontend_port)
        write_frontend_config(args.backend_port)
        start_frontend(args.frontend_port)
        frontend_url = "http://127.0.0.1:%d" % args.frontend_port

    def state(flag: str) -> str:
        return "on" if features.get(flag) else "off (dependency not installed)"

    print("\n" + "=" * 62)
    print("  AI Doctor - local development stack")
    print("=" * 62)
    print("  Backend API   : http://127.0.0.1:%d" % args.backend_port)
    print("  API docs      : http://127.0.0.1:%d/docs" % args.backend_port)
    if frontend_url:
        print("  Frontend      : %s" % frontend_url)
    print("  Local models  :")
    print("    fracture (TensorFlow) : %s" % state("ENABLE_FRACTURE"))
    print("    OCR (PaddleOCR)       : %s" % state("ENABLE_OCR"))
    print("    voice (Whisper)       : %s" % state("ENABLE_VOICE"))
    print("  Config file   : %s" % (BACKEND_DIR / ".env"))
    print("  Press Ctrl+C to stop.")
    print("=" * 62 + "\n")

    if frontend_url and not args.no_browser:
        threading.Timer(1.5, webbrowser.open, args=(frontend_url,)).start()

    import uvicorn

    try:
        uvicorn.run(
            "app.main:app",
            host="127.0.0.1",
            port=args.backend_port,
            reload=args.reload,
            reload_dirs=[str(BACKEND_DIR / "app")] if args.reload else None,
            log_level=(os.environ.get("LOG_LEVEL") or "info").lower(),
        )
    except KeyboardInterrupt:
        pass
    print("\nStopped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
