import json  # For reading JSON files
import numpy as np  # For numerical operations (not used here but could be used for further processing)

# Function to extract text from a JSON file generated by an OCR model
def extract_text_from_json(json_path):
    with open(json_path) as f:
        data = json.load(f)  # Load the JSON file content

    texts = data['rec_texts']  # Extract recognized text
    boxes = data['rec_boxes']  # Extract corresponding bounding boxes

    entries = []  # To store individual entries with coordinates
    for i, box in enumerate(boxes):
        x_min, y_min, x_max, y_max = box  # Unpack box coordinates
        center_y = (y_min + y_max) / 2  # Compute vertical center
        entries.append({
            'text': texts[i],  # Corresponding text
            'y_min': y_min,
            'y_max': y_max,
            'x_min': x_min,
            'x_max': x_max,
            'center_y': center_y  # Used for vertical sorting
        })

    # Sort entries by their vertical center (top to bottom)
    sorted_entries = sorted(entries, key=lambda e: e['center_y'])

    rows = []  # List of text rows
    current_row = [sorted_entries[0]]  # Start with the first entry

    # Group entries into rows based on vertical overlap
    for entry in sorted_entries[1:]:
        last_in_row = current_row[-1]  # Last entry in current row

        # Calculate vertical overlap between entries
        y_overlap = (min(entry['y_max'], last_in_row['y_max']) -
                     max(entry['y_min'], last_in_row['y_min']))

        # Calculate the minimum height between two boxes
        height = min(entry['y_max'] - entry['y_min'],
                     last_in_row['y_max'] - last_in_row['y_min'])

        # If overlap is significant, consider it part of the same row
        if y_overlap > height * 0.6:
            current_row.append(entry)
        else:
            # Sort the row horizontally (left to right) and save it
            rows.append(sorted(current_row, key=lambda e: e['x_min']))
            current_row = [entry]  # Start a new row

    # Add the last row after loop ends
    rows.append(sorted(current_row, key=lambda e: e['x_min']))

    output_lines = []  # Final reconstructed text lines
    for row in rows:
        line_parts = []
        current_x = 0  # Track horizontal position

        for i, entry in enumerate(row):
            # If there's a gap between words, add space accordingly
            if entry['x_min'] > current_x and i > 0:
                gap = entry['x_min'] - current_x
                line_parts.append(' ' * max(1, int(gap / 10)))  # Add space based on gap

            line_parts.append(entry['text'])  # Add the actual text
            current_x = entry['x_max']  # Update x position

        output_lines.append(''.join(line_parts))  # Join row parts into a full line

    txt = ''
    for line in output_lines:
        txt += line + '\n'  # Combine all lines into one string

    return txt  # Return the full reconstructed text
